import productImage01 from "./images/productImage.png";
// import productImage02 from "./images/productImage.png";

const Products = [
  {
    id: 1,
    productName: "Fancy Product",
    productRating: "",
    productPrice02: "$40.00 - $80.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 2,
    productName: "Special Item",
    productRating: "*****",
    productPrice01: "$20.00",
    productPrice02: " $18.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 3,
    productName: "Sale Item",
    productRating: "",
    productPrice01: "$50.00",
    productPrice02: " $25.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 4,
    productName: "Popular Item",
    productRating: "*****",
    productPrice02: "$40.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 5,
    productName: "Sale Item",
    productRating: "",
    productPrice01: "$50.00",
    productPrice02: " $25.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 6,
    productName: "Fancy Product",
    productRating: "",
    productPrice02: "$120.00 - $280.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 7,
    productName: "Special Item",
    productRating: "*****",
    productPrice01: "$20.00",
    productPrice02: " $18.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
  {
    id: 8,
    productName: "Popular Item",
    productRating: "*****",
    productPrice02: "$40.00",
    productImage: productImage01,
    productButton: "Add to Cart",
    disabled: false,
    hidden: true,
  },
];

export default Products;
